version: '3.8'

services:
  cache_server_0:
    build: .
    ports:
      - "9527:8080" # 外部端口映射为9527
    environment:
      - ID=0

  cache_server_1:
    build: .
    ports:
      - "9528:8080"
    environment:
      - ID=1

  cache_server_2:
    build: .
    ports:
      - "9529:8080"
    environment:
      - ID=2